packages:
  - "apps/*"
  - "my-startups/carebot-japan/web"
  - "my-startups/japan-unlocked"
  - "my-startups/kanso-templates"
  - "packages/*"
allowBuilds:
  '@sentry/cli': false
  sharp: true
  unrs-resolver: true
